export default function Head() {
    return (
        <>
            <title>Digital Hitchhiker Photography | Gallery</title>
            <meta name="viewport" content="initial-scale=1.0, width=device-width" />
            <meta name="description" content="Generated by NutnButTreys" />
            <link rel="icon" href="/favicon.ico" />
        </>
    );
}